In [8]:
#Multipurpose porgramming Language
    #Desktop Application 
    #Web application 
    #Network Application 
    #Database Application 
    #Games 
    #Data Analytics
    #Data Science 
    #Machine Learning 
    #Artificial Intelligence or Deep Learning
    #IoT Application 
    #Automations 

In [9]:
#Functional Programming - C progamming 
#OOP - C++ 
#Scripting Language - Perl and Shell 
#Modular Programming - Modula 3 
#Syntax of Python - C and ABC programming 

In [10]:
#A code which create 6 digits OTP numbers 10 times 
from random import *
for i in range(0,10):
    print(randint(0,9),randint(0,9),randint(0,9),randint(0,9),randint(0,9),randint(0,9))

6 0 8 9 6 8
0 8 9 5 6 4
3 8 2 0 8 6
0 9 6 0 4 8
0 8 7 1 6 5
4 5 7 3 4 8
9 0 4 6 1 9
5 8 1 7 3 0
5 7 8 4 0 7
6 1 0 5 9 9


In [11]:
sales = 150.5

In [13]:
type(sales)

float

In [14]:
quantity = 10

In [15]:
type(quantity)

int

In [16]:
custname = 'Rahul'

In [17]:
type(custname)

str

In [19]:
output = sales>100

In [21]:
type(output)

bool

In [22]:
#Dynamically Typed Programming Language 

In [23]:
#Identifiers
    #Alphabets (Anywhere), _(Anywhere), numbers(Cannot be at the start)  
sales = 10
_sales =10
sales_ = 10
sa_les = 10

In [28]:
10sales = 10

SyntaxError: invalid syntax (Temp/ipykernel_17276/733264514.py, line 1)

In [29]:
sales10 = 10

In [30]:
sales10

10

In [26]:
_sales

10

In [31]:
sa_10les = 10

In [32]:
sa_10les

10

In [33]:
sales = 150
SALES = 160

In [34]:
sales

150

In [35]:
SALES

160

In [36]:
import keyword
keyword.kwlist

['False',
 'None',
 'True',
 '__peg_parser__',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [38]:
For  = 'Rahul'

In [39]:
For

'Rahul'

In [40]:
#Single Values 

In [41]:
#Python Collection Datatypes (Data Structures)
    #List - Hetrogeneous , Mutable
    #Tuple - Hetrogeous, Immutable
    #Dictionary
    #Set
        #Frozenset

In [81]:
ages = [21,23,32,22,34,33,21]

In [44]:
type(ages)

list

In [46]:
len(ages)

7

In [47]:
sum(ages)

186

In [48]:
min(ages)

21

In [49]:
max(ages)

34

In [50]:
list1 = ['A',10, 10.5,True]
sum(list1)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [52]:
ages[3]

22

In [53]:
ages

[21, 23, 32, 22, 34, 33, 21]

In [55]:
ages[2:5]

[32, 22, 34]

In [56]:
ages[-4]

22

In [60]:
ages[0:3:1]

[21, 23, 32]

In [62]:
ages[3:0:-2]

[22, 23]

In [63]:
ages[-6:5]

[23, 32, 22, 34]

In [65]:
ages[6:-6:-1]

[21, 33, 34, 22, 32]

In [67]:
ages.append(100)

In [70]:
ages.append([101,102,103])

In [73]:
ages[-1][1]

102

In [75]:
del ages[-1]

In [77]:
ages.extend([101,102,103])

In [78]:
ages

[21, 23, 32, 22, 34, 33, 21, 100, 101, 102, 103]

In [79]:
ages.clear()

In [83]:
ages1 = ages.copy()

In [89]:
ages[0]=22

In [93]:
id(ages)

2434333673024

In [94]:
id(ages1)

2434332141760

In [86]:
ages2 = ages

In [95]:
id(ages2)

2434333673024

In [96]:
ages.count(22)

2

In [97]:
ages

[22, 23, 32, 22, 34, 33, 21]

In [99]:
ages.index(32)

2

In [100]:
ages.insert(4,100)

In [102]:
ages.pop()

21

In [104]:
ages.pop(3)

22

In [105]:
ages

[22, 23, 32, 100, 34, 33]

In [106]:
ages.remove(100)

In [108]:
ages.reverse()

In [110]:
ages.sort()

In [112]:
ages.sort(reverse=True)

In [113]:
ages

[34, 33, 32, 23, 22]

In [114]:
salary = (21,23,23,21,22,33)

In [115]:
type(salary)

tuple

In [117]:
salary[2]=43

TypeError: 'tuple' object does not support item assignment

In [118]:
salary.count(23)

2

In [119]:
salary.index(23)

1

In [120]:
len(salary)

6

In [121]:
max(salary)

33

In [122]:
min(salary)

21

In [123]:
sum(salary)

143

In [124]:
del salary

In [125]:
salary

NameError: name 'salary' is not defined

In [130]:
#Dictionaries
stu_details = {'stu_id':[1,2,3,4,5], 'stu_name':['A','B','C','D','E'], 'stu_region':['N','S','E','W','W'] }

In [131]:
type(stu_details)

dict

In [133]:
len(stu_details)

3

In [135]:
stu_details.get('stu_name')

['A', 'B', 'C', 'D', 'E']

In [136]:
stu_details['stu_name']

['A', 'B', 'C', 'D', 'E']

In [137]:
stu_details.items()

dict_items([('stu_id', [1, 2, 3, 4, 5]), ('stu_name', ['A', 'B', 'C', 'D', 'E']), ('stu_region', ['N', 'S', 'E', 'W', 'W'])])

In [138]:
stu_details.keys()

dict_keys(['stu_id', 'stu_name', 'stu_region'])

In [139]:
stu_details.values()

dict_values([[1, 2, 3, 4, 5], ['A', 'B', 'C', 'D', 'E'], ['N', 'S', 'E', 'W', 'W']])

In [141]:
stu_details.pop('stu_region')

['N', 'S', 'E', 'W', 'W']

In [142]:
stu_details

{'stu_id': [1, 2, 3, 4, 5], 'stu_name': ['A', 'B', 'C', 'D', 'E']}

In [144]:
stu_details.popitem()

('stu_name', ['A', 'B', 'C', 'D', 'E'])

In [146]:
stu_details['stu_name'] = ['a','b','c','d','e']

In [148]:
stu_details.setdefault('stu_region')

In [150]:
stu_details['stu_region'] = ['N','S','W','E','W']

In [151]:
stu_details

{'stu_id': [1, 2, 3, 4, 5],
 'stu_name': ['a', 'b', 'c', 'd', 'e'],
 'stu_region': ['N', 'S', 'W', 'E', 'W']}

In [152]:
dict1 = {1:2,3:4,5:6}
dict2 = {1:10, 7:8}

In [153]:
dict1.update(dict2)

In [154]:
dict1

{1: 10, 3: 4, 5: 6, 7: 8}

In [156]:
import pandas as pd
pd.DataFrame(stu_details)

stu_id stu_name stu_region
0       1        a          N
1       2        b          S
2       3        c          W
3       4        d          E
4       5        e          W

In [176]:
#Sets
set1 = {1,2,3,3,3,3,4,5,6,6,6,7,8,8,8,9,9}

In [158]:
set1

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [159]:
set1[0]

TypeError: 'set' object is not subscriptable

In [168]:
len(set1)

9

In [162]:
min(set1)

1

In [163]:
max(set1)

9

In [164]:
sum(set1)

45

In [165]:
del set1

In [171]:
set1.add([10,11,12])

TypeError: unhashable type: 'list'

In [172]:
set1.update([11,12,13])

In [174]:
set1.clear()

In [205]:
set1.discard(9)

In [206]:
set1

{1, 2, 3, 4, 5, 6, 7}

In [207]:
set1.remove(8)

KeyError: 8

In [209]:
set1.pop()

1

In [211]:
set1

{2, 3, 4, 5, 6, 7}

In [221]:
set1 = {1,2,3,4,5,6}
set2 = {4,5,6}
set3 = {5,6,7,8}
set4 = {9,10,11,12}

In [213]:
set1.difference(set3)

{1, 2, 3, 4}

In [216]:
set1.difference_update(set3)
set1

{1, 2, 3, 4}

In [214]:
set1.symmetric_difference(set3)

{1, 2, 3, 4, 7, 8}

In [218]:
set1.symmetric_difference_update(set3)
set1

{1, 2, 3, 4, 7, 8}

In [215]:
set1.intersection(set3)

{5, 6}

In [220]:
set1.intersection_update(set3)
set1

{5, 6}

In [222]:
set1 = {1,2,3,4,5,6}
set2 = {4,5,6}
set3 = {5,6,7,8}
set4 = {9,10,11,12}

In [224]:
set1.union(set3)

{1, 2, 3, 4, 5, 6, 7, 8}

In [225]:
set1.isdisjoint(set4)

True

In [226]:
set1.issuperset(set2)

True

In [227]:
set2.issubset(set1)

True

In [229]:
fsset = frozenset(set1)

In [231]:
fsset

frozenset({1, 2, 3, 4, 5, 6})

In [232]:
#Operators in Python
    #Arithmatic 
    #Relational or Comparison 
    #Equality
    #Assignment 
    #Ternary
    #Special 

In [234]:
#Arithmatic

    #+ - Addition
    #- - Subtraction
    #* - Multiplication
    #/ - Division
    #% - Modulo
    #// - Floor Div
    #** - Power
    
a = 10 
b = 3 
print('a+b:', a+b)
print('a-b:', a-b)
print('a*b:', a*b)
print('a/b:', a/b)
print('a%b:', a%b)
print('a//b:', a//b)
print('a**b:', a**b)

a+b: 13
a-b: 7
a*b: 30
a/b: 3.3333333333333335
a%b: 1
a//b: 3
a**b: 1000


In [238]:
#Relational 
a = 10 
b = 3
print('a<b:', a<b)
print('a<=b:', a<=b)
print('a>b:', a>b)
print('a>=b:', a>=b)

a<b: False
a<=b: False
a>b: True
a>=b: True


In [244]:
#Equality 
a = 10 
b = 3 
print('a==b:',a==b)
print('a!=b:',a!=b)

a==b: False
a!=b: True


In [246]:
#Assignment
a = 10 
a+=20
a-=50
a

-20

In [247]:
a = 7
b = 4
x = a if a>b else b
x

7

In [248]:
a = 7 
b = 4 
c = 5
x = a if a>b>c else b if b>c else c
x

5

In [249]:
#Special Operators
    #Identity 
        #is 
        #is not

    #Membership 
        #in
        #not in

In [257]:
a = 256
b = 256
print(id(a))
print(id(b))

2434217044368
2434217044368


In [258]:
a is b

True

In [259]:
list1 = [1,2,3,4,5]
5 in list1

True

In [260]:
#Control statements 
    #if and else
    #for 
    #while

In [269]:
marks = 45
if marks<=35:
    print('You failed the exam')
    print('Hi')
else:
    print('You passed the exam')
print('Hello')    

You passed the exam
Hello


In [272]:
marks = 65
if marks<=35:
    print('You are failed the exam')
elif marks>35 and marks<=60:
    print('You got avg marks')
else: 
    print('You got excellent marks')

You got excellent marks


In [277]:
#For loops
sales = [432,232,242,112]
for i in sales:
    print(i*0.5)

216.0
116.0
121.0
56.0


In [279]:
sales = [3432,1234,3224,2322]
profit = [432,222,121,223]

In [284]:
for i in range(0,len(sales)):
    print(profit[i]/sales[i])

0.1258741258741259
0.17990275526742303
0.03753101736972705
0.09603789836347976


In [282]:
list(range(0,4))

[0, 1, 2, 3]

In [288]:
#while loop
coupouns = 5
utilized = 0

while utilized<coupouns:
    print('Total coupouns left are: ', coupouns-utilized)
    utilized=utilized+1
print('No coupons left')

Total coupouns left are:  5
Total coupouns left are:  4
Total coupouns left are:  3
Total coupouns left are:  2
Total coupouns left are:  1
No coupons left


In [294]:
number = 5
if number<0:
    print('There is no factorial of the negative number')
else:
    result = 1 
    while number>=1: 
        result = result*number
        number=number-1
    print(result)

120


In [309]:
#User Defined Functions in Python

def calculator(num1,num2,operation='all'):
    if operation=='sum':
        print('num1+num2: ', num1+num2)
    elif operation=='sub':
        print('num1-num2: ', num1-num2)
    elif operation=='mul':
        print('num1*num2: ', num1*num2)
    elif operation=='div':
        print('num1/num2: ', num1/num2)
    elif operation=='all':
        print('num1+num2: ', num1+num2)
        print('num1-num2: ', num1-num2)
        print('num1*num2: ', num1*num2)
        print('num1/num2: ', num1/num2)
    else:
        print('Enter the correct options')

In [311]:
output = calculator(10,3)

num1+num2:  13
num1-num2:  7
num1*num2:  30
num1/num2:  3.3333333333333335


In [313]:
type(output)

NoneType

In [320]:
#User Defined Functions in Python

def calculator(num1,num2,operation='all'):
    if operation=='sum':
        return('num1+num2: ', num1+num2)
    elif operation=='sub':
        return('num1-num2: ', num1-num2)
    elif operation=='mul':
        return('num1*num2: ', num1*num2)
    elif operation=='div':
        return('num1/num2: ', num1/num2)
    elif operation=='all':
        return{'num1+num2: ': num1+num2, 'num1-num2:': num1-num2,'num1*num2:': num1*num2,'num1/num2:': num1/num2  }
    else:
        return('Enter the correct options')

In [321]:
output = calculator(10,3)

In [322]:
output

{'num1+num2: ': 13,
 'num1-num2:': 7,
 'num1*num2:': 30,
 'num1/num2:': 3.3333333333333335}

In [323]:
#Variable length arguement 
def addition(*args):
    result = 0 
    for i in args:
        result = result + i 
    print(result)

In [324]:
addition(10,20,30,40,50)

150


In [326]:
p = 10 
def f1():
    global p
    p = 1000
    print('F1:', p)
    
f1()

def f2():
    print('F2:', p)
    
f2()

F1: 1000
F2: 1000


In [327]:
p

1000

In [328]:
#Numpy

In [329]:
import numpy as np

In [330]:
np.__version__

'1.23.0'

In [357]:
#Array
list1 = [True]

In [333]:
type(list1)

list

In [338]:
type(list1[3])

bool

In [358]:
array1 = np.array(list1)

In [359]:
array1

array([ True])

In [353]:
type(array1[2])

numpy.float64

In [362]:
for i in range(0,len(sales)):
    print(profit[i]/sales[i])

0.1258741258741259
0.17990275526742303
0.03753101736972705
0.09603789836347976


In [363]:
sales_array = np.array(sales)
profit_array = np.array(profit)

In [364]:
sales_array

array([3432, 1234, 3224, 2322])

In [376]:
type(profit_array)

numpy.ndarray

In [366]:
profit_array/sales_array

array([0.12587413, 0.17990276, 0.03753102, 0.0960379 ])

In [371]:
sales_us = [3245,3322,1221,3121]
sales_eu = [4322,1212,3232,1211]
sales_jp = [5422,1211,1212,2323]

profit_us = [421,121,323,121]
profit_eu = [543,232,121,212]
profit_jp = [543,221,121,211]

In [373]:
sales_matrix = np.array([sales_us,sales_eu,sales_jp])

In [375]:
type(sales_matrix)

numpy.ndarray

In [377]:
profit_matrix = np.array([profit_us,profit_eu,profit_jp])

In [378]:
profit_matrix

array([[421, 121, 323, 121],
       [543, 232, 121, 212],
       [543, 221, 121, 211]])

In [379]:
sales_matrix

array([[3245, 3322, 1221, 3121],
       [4322, 1212, 3232, 1211],
       [5422, 1211, 1212, 2323]])

In [380]:
profit_matrix/sales_matrix

array([[0.12973806, 0.03642384, 0.26453726, 0.03876963],
       [0.12563628, 0.19141914, 0.03743812, 0.17506193],
       [0.10014755, 0.18249381, 0.09983498, 0.09083082]])

In [381]:
sales_matrix

array([[3245, 3322, 1221, 3121],
       [4322, 1212, 3232, 1211],
       [5422, 1211, 1212, 2323]])

In [382]:
np.average(sales_matrix)

2587.8333333333335

In [383]:
np.average(sales_matrix,axis=1)

array([2727.25, 2494.25, 2542.  ])

In [384]:
np.average(sales_matrix,axis=0)

array([4329.66666667, 1915.        , 1888.33333333, 2218.33333333])

In [387]:
sales_matrix

array([[3245, 3322, 1221, 3121],
       [4322, 1212, 3232, 1211],
       [5422, 1211, 1212, 2323]])

In [386]:
sales_matrix[np.where(sales_matrix>3300)]

array([3322, 4322, 5422])

In [388]:
np.where(sales_matrix>3300)

(array([0, 1, 2], dtype=int64), array([1, 0, 0], dtype=int64))

In [389]:
sales_matrix[2,2]

1212

In [390]:
sales_matrix[1:3,1:3]

array([[1212, 3232],
       [1211, 1212]])

In [391]:
#Pandas 

In [392]:
import pandas as pd

In [393]:
pd.__version__

'1.3.4'

In [394]:
stu_details 

{'stu_id': [1, 2, 3, 4, 5],
 'stu_name': ['a', 'b', 'c', 'd', 'e'],
 'stu_region': ['N', 'S', 'W', 'E', 'W']}

In [408]:
stu_marks = {'s_id':[1,2,3,4,6],
            's_marks':[12,21,22,11,22],
            's_sub':['Py','Tab','R','Py','R']}

In [409]:
df1 = pd.DataFrame(stu_details)

In [410]:
df2 = pd.DataFrame(stu_marks)

In [411]:
df1

stu_id stu_name stu_region
0       1        a          N
1       2        b          S
2       3        c          W
3       4        d          E
4       5        e          W

In [412]:
df2

s_id  s_marks s_sub
0     1       12    Py
1     2       21   Tab
2     3       22     R
3     4       11    Py
4     6       22     R

In [417]:
pd.merge(pd.merge(df1,df2,left_on='stu_id',right_on='s_id',how='outer'),df3, left_on=,right_on=,how=)

stu_id stu_name stu_region  s_id  s_marks s_sub
0     1.0        a          N   1.0     12.0    Py
1     2.0        b          S   2.0     21.0   Tab
2     3.0        c          W   3.0     22.0     R
3     4.0        d          E   4.0     11.0    Py
4     5.0        e          W   NaN      NaN   NaN
5     NaN      NaN        NaN   6.0     22.0     R

In [418]:
df1

stu_id stu_name stu_region
0       1        a          N
1       2        b          S
2       3        c          W
3       4        d          E
4       5        e          W

In [420]:
#Dictionaries
stu_details_Ind = {'stu_id':[1,2,3,4,5], 'stu_name':['A','B','C','D','E'], 'stu_region':['N_IN','S_IN','E_IN','W_IN','W_IN'] }

In [421]:
stu_details_US = {'stu_id':[6,7,8,9,5], 'stu_name':['P','Q','R','S','E'], 'stu_region':['N_US','S_US','E_US','W_US','W_IN'] }

In [423]:
df_in = pd.DataFrame(stu_details_Ind)

In [424]:
df_us = pd.DataFrame(stu_details_US)

In [425]:
df_in

stu_id stu_name stu_region
0       1        A       N_IN
1       2        B       S_IN
2       3        C       E_IN
3       4        D       W_IN
4       5        E       W_IN

In [426]:
df_us

stu_id stu_name stu_region
0       6        P       N_US
1       7        Q       S_US
2       8        R       E_US
3       9        S       W_US
4       5        E       W_IN

In [430]:
pd.concat([df_in,df_us]).reset_index().drop(columns='index').drop_duplicates()

stu_id stu_name stu_region
0       1        A       N_IN
1       2        B       S_IN
2       3        C       E_IN
3       4        D       W_IN
4       5        E       W_IN
5       6        P       N_US
6       7        Q       S_US
7       8        R       E_US
8       9        S       W_US

In [436]:
pd.concat([df_in,df_us],axis=0).reset_index().drop(columns='index').drop_duplicates()

stu_id stu_name stu_region
0       1        A       N_IN
1       2        B       S_IN
2       3        C       E_IN
3       4        D       W_IN
4       5        E       W_IN
5       6        P       N_US
6       7        Q       S_US
7       8        R       E_US
8       9        S       W_US